/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubgroupsRouteImport } from './routes/subgroups'
import { Route as Notes3RouteImport } from './routes/notes-3'
import { Route as Notes2RouteImport } from './routes/notes-2'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as HomomorphismsRouteImport } from './routes/homomorphisms'
import { Route as ClockRouteImport } from './routes/clock'
import { Route as IndexRouteImport } from './routes/index'

const SubgroupsRoute = SubgroupsRouteImport.update({
  id: '/subgroups',
  path: '/subgroups',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes3Route = Notes3RouteImport.update({
  id: '/notes-3',
  path: '/notes-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes2Route = Notes2RouteImport.update({
  id: '/notes-2',
  path: '/notes-2',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const HomomorphismsRoute = HomomorphismsRouteImport.update({
  id: '/homomorphisms',
  path: '/homomorphisms',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockRoute = ClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clock': typeof ClockRoute
  '/homomorphisms': typeof HomomorphismsRoute
  '/notes': typeof NotesRoute
  '/notes-2': typeof Notes2Route
  '/notes-3': typeof Notes3Route
  '/subgroups': typeof SubgroupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clock': typeof ClockRoute
  '/homomorphisms': typeof HomomorphismsRoute
  '/notes': typeof NotesRoute
  '/notes-2': typeof Notes2Route
  '/notes-3': typeof Notes3Route
  '/subgroups': typeof SubgroupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clock': typeof ClockRoute
  '/homomorphisms': typeof HomomorphismsRoute
  '/notes': typeof NotesRoute
  '/notes-2': typeof Notes2Route
  '/notes-3': typeof Notes3Route
  '/subgroups': typeof SubgroupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clock'
    | '/homomorphisms'
    | '/notes'
    | '/notes-2'
    | '/notes-3'
    | '/subgroups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clock'
    | '/homomorphisms'
    | '/notes'
    | '/notes-2'
    | '/notes-3'
    | '/subgroups'
  id:
    | '__root__'
    | '/'
    | '/clock'
    | '/homomorphisms'
    | '/notes'
    | '/notes-2'
    | '/notes-3'
    | '/subgroups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClockRoute: typeof ClockRoute
  HomomorphismsRoute: typeof HomomorphismsRoute
  NotesRoute: typeof NotesRoute
  Notes2Route: typeof Notes2Route
  Notes3Route: typeof Notes3Route
  SubgroupsRoute: typeof SubgroupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subgroups': {
      id: '/subgroups'
      path: '/subgroups'
      fullPath: '/subgroups'
      preLoaderRoute: typeof SubgroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-3': {
      id: '/notes-3'
      path: '/notes-3'
      fullPath: '/notes-3'
      preLoaderRoute: typeof Notes3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-2': {
      id: '/notes-2'
      path: '/notes-2'
      fullPath: '/notes-2'
      preLoaderRoute: typeof Notes2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homomorphisms': {
      id: '/homomorphisms'
      path: '/homomorphisms'
      fullPath: '/homomorphisms'
      preLoaderRoute: typeof HomomorphismsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClockRoute: ClockRoute,
  HomomorphismsRoute: HomomorphismsRoute,
  NotesRoute: NotesRoute,
  Notes2Route: Notes2Route,
  Notes3Route: Notes3Route,
  SubgroupsRoute: SubgroupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
