/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SubgroupsRouteImport } from './routes/subgroups'
import { Route as RsaSimulationRouteImport } from './routes/rsa-simulation'
import { Route as Notes9RouteImport } from './routes/notes-9'
import { Route as Notes8RouteImport } from './routes/notes-8'
import { Route as Notes7RouteImport } from './routes/notes-7'
import { Route as Notes6RouteImport } from './routes/notes-6'
import { Route as Notes5RouteImport } from './routes/notes-5'
import { Route as Notes4RouteImport } from './routes/notes-4'
import { Route as Notes3RouteImport } from './routes/notes-3'
import { Route as Notes2RouteImport } from './routes/notes-2'
import { Route as Notes14RouteImport } from './routes/notes-14'
import { Route as Notes13RouteImport } from './routes/notes-13'
import { Route as Notes12RouteImport } from './routes/notes-12'
import { Route as Notes11RouteImport } from './routes/notes-11'
import { Route as Notes10RouteImport } from './routes/notes-10'
import { Route as NotesRouteImport } from './routes/notes'
import { Route as HomomorphismsRouteImport } from './routes/homomorphisms'
import { Route as EccCalculatorRouteImport } from './routes/ecc-calculator'
import { Route as DiracNotationLabRouteImport } from './routes/dirac-notation-lab'
import { Route as ClockRouteImport } from './routes/clock'
import { Route as IndexRouteImport } from './routes/index'

const SubgroupsRoute = SubgroupsRouteImport.update({
  id: '/subgroups',
  path: '/subgroups',
  getParentRoute: () => rootRouteImport,
} as any)
const RsaSimulationRoute = RsaSimulationRouteImport.update({
  id: '/rsa-simulation',
  path: '/rsa-simulation',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes9Route = Notes9RouteImport.update({
  id: '/notes-9',
  path: '/notes-9',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes8Route = Notes8RouteImport.update({
  id: '/notes-8',
  path: '/notes-8',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes7Route = Notes7RouteImport.update({
  id: '/notes-7',
  path: '/notes-7',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes6Route = Notes6RouteImport.update({
  id: '/notes-6',
  path: '/notes-6',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes5Route = Notes5RouteImport.update({
  id: '/notes-5',
  path: '/notes-5',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes4Route = Notes4RouteImport.update({
  id: '/notes-4',
  path: '/notes-4',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes3Route = Notes3RouteImport.update({
  id: '/notes-3',
  path: '/notes-3',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes2Route = Notes2RouteImport.update({
  id: '/notes-2',
  path: '/notes-2',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes14Route = Notes14RouteImport.update({
  id: '/notes-14',
  path: '/notes-14',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes13Route = Notes13RouteImport.update({
  id: '/notes-13',
  path: '/notes-13',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes12Route = Notes12RouteImport.update({
  id: '/notes-12',
  path: '/notes-12',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes11Route = Notes11RouteImport.update({
  id: '/notes-11',
  path: '/notes-11',
  getParentRoute: () => rootRouteImport,
} as any)
const Notes10Route = Notes10RouteImport.update({
  id: '/notes-10',
  path: '/notes-10',
  getParentRoute: () => rootRouteImport,
} as any)
const NotesRoute = NotesRouteImport.update({
  id: '/notes',
  path: '/notes',
  getParentRoute: () => rootRouteImport,
} as any)
const HomomorphismsRoute = HomomorphismsRouteImport.update({
  id: '/homomorphisms',
  path: '/homomorphisms',
  getParentRoute: () => rootRouteImport,
} as any)
const EccCalculatorRoute = EccCalculatorRouteImport.update({
  id: '/ecc-calculator',
  path: '/ecc-calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const DiracNotationLabRoute = DiracNotationLabRouteImport.update({
  id: '/dirac-notation-lab',
  path: '/dirac-notation-lab',
  getParentRoute: () => rootRouteImport,
} as any)
const ClockRoute = ClockRouteImport.update({
  id: '/clock',
  path: '/clock',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/clock': typeof ClockRoute
  '/dirac-notation-lab': typeof DiracNotationLabRoute
  '/ecc-calculator': typeof EccCalculatorRoute
  '/homomorphisms': typeof HomomorphismsRoute
  '/notes': typeof NotesRoute
  '/notes-10': typeof Notes10Route
  '/notes-11': typeof Notes11Route
  '/notes-12': typeof Notes12Route
  '/notes-13': typeof Notes13Route
  '/notes-14': typeof Notes14Route
  '/notes-2': typeof Notes2Route
  '/notes-3': typeof Notes3Route
  '/notes-4': typeof Notes4Route
  '/notes-5': typeof Notes5Route
  '/notes-6': typeof Notes6Route
  '/notes-7': typeof Notes7Route
  '/notes-8': typeof Notes8Route
  '/notes-9': typeof Notes9Route
  '/rsa-simulation': typeof RsaSimulationRoute
  '/subgroups': typeof SubgroupsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/clock': typeof ClockRoute
  '/dirac-notation-lab': typeof DiracNotationLabRoute
  '/ecc-calculator': typeof EccCalculatorRoute
  '/homomorphisms': typeof HomomorphismsRoute
  '/notes': typeof NotesRoute
  '/notes-10': typeof Notes10Route
  '/notes-11': typeof Notes11Route
  '/notes-12': typeof Notes12Route
  '/notes-13': typeof Notes13Route
  '/notes-14': typeof Notes14Route
  '/notes-2': typeof Notes2Route
  '/notes-3': typeof Notes3Route
  '/notes-4': typeof Notes4Route
  '/notes-5': typeof Notes5Route
  '/notes-6': typeof Notes6Route
  '/notes-7': typeof Notes7Route
  '/notes-8': typeof Notes8Route
  '/notes-9': typeof Notes9Route
  '/rsa-simulation': typeof RsaSimulationRoute
  '/subgroups': typeof SubgroupsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/clock': typeof ClockRoute
  '/dirac-notation-lab': typeof DiracNotationLabRoute
  '/ecc-calculator': typeof EccCalculatorRoute
  '/homomorphisms': typeof HomomorphismsRoute
  '/notes': typeof NotesRoute
  '/notes-10': typeof Notes10Route
  '/notes-11': typeof Notes11Route
  '/notes-12': typeof Notes12Route
  '/notes-13': typeof Notes13Route
  '/notes-14': typeof Notes14Route
  '/notes-2': typeof Notes2Route
  '/notes-3': typeof Notes3Route
  '/notes-4': typeof Notes4Route
  '/notes-5': typeof Notes5Route
  '/notes-6': typeof Notes6Route
  '/notes-7': typeof Notes7Route
  '/notes-8': typeof Notes8Route
  '/notes-9': typeof Notes9Route
  '/rsa-simulation': typeof RsaSimulationRoute
  '/subgroups': typeof SubgroupsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/clock'
    | '/dirac-notation-lab'
    | '/ecc-calculator'
    | '/homomorphisms'
    | '/notes'
    | '/notes-10'
    | '/notes-11'
    | '/notes-12'
    | '/notes-13'
    | '/notes-14'
    | '/notes-2'
    | '/notes-3'
    | '/notes-4'
    | '/notes-5'
    | '/notes-6'
    | '/notes-7'
    | '/notes-8'
    | '/notes-9'
    | '/rsa-simulation'
    | '/subgroups'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/clock'
    | '/dirac-notation-lab'
    | '/ecc-calculator'
    | '/homomorphisms'
    | '/notes'
    | '/notes-10'
    | '/notes-11'
    | '/notes-12'
    | '/notes-13'
    | '/notes-14'
    | '/notes-2'
    | '/notes-3'
    | '/notes-4'
    | '/notes-5'
    | '/notes-6'
    | '/notes-7'
    | '/notes-8'
    | '/notes-9'
    | '/rsa-simulation'
    | '/subgroups'
  id:
    | '__root__'
    | '/'
    | '/clock'
    | '/dirac-notation-lab'
    | '/ecc-calculator'
    | '/homomorphisms'
    | '/notes'
    | '/notes-10'
    | '/notes-11'
    | '/notes-12'
    | '/notes-13'
    | '/notes-14'
    | '/notes-2'
    | '/notes-3'
    | '/notes-4'
    | '/notes-5'
    | '/notes-6'
    | '/notes-7'
    | '/notes-8'
    | '/notes-9'
    | '/rsa-simulation'
    | '/subgroups'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ClockRoute: typeof ClockRoute
  DiracNotationLabRoute: typeof DiracNotationLabRoute
  EccCalculatorRoute: typeof EccCalculatorRoute
  HomomorphismsRoute: typeof HomomorphismsRoute
  NotesRoute: typeof NotesRoute
  Notes10Route: typeof Notes10Route
  Notes11Route: typeof Notes11Route
  Notes12Route: typeof Notes12Route
  Notes13Route: typeof Notes13Route
  Notes14Route: typeof Notes14Route
  Notes2Route: typeof Notes2Route
  Notes3Route: typeof Notes3Route
  Notes4Route: typeof Notes4Route
  Notes5Route: typeof Notes5Route
  Notes6Route: typeof Notes6Route
  Notes7Route: typeof Notes7Route
  Notes8Route: typeof Notes8Route
  Notes9Route: typeof Notes9Route
  RsaSimulationRoute: typeof RsaSimulationRoute
  SubgroupsRoute: typeof SubgroupsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/subgroups': {
      id: '/subgroups'
      path: '/subgroups'
      fullPath: '/subgroups'
      preLoaderRoute: typeof SubgroupsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rsa-simulation': {
      id: '/rsa-simulation'
      path: '/rsa-simulation'
      fullPath: '/rsa-simulation'
      preLoaderRoute: typeof RsaSimulationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-9': {
      id: '/notes-9'
      path: '/notes-9'
      fullPath: '/notes-9'
      preLoaderRoute: typeof Notes9RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-8': {
      id: '/notes-8'
      path: '/notes-8'
      fullPath: '/notes-8'
      preLoaderRoute: typeof Notes8RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-7': {
      id: '/notes-7'
      path: '/notes-7'
      fullPath: '/notes-7'
      preLoaderRoute: typeof Notes7RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-6': {
      id: '/notes-6'
      path: '/notes-6'
      fullPath: '/notes-6'
      preLoaderRoute: typeof Notes6RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-5': {
      id: '/notes-5'
      path: '/notes-5'
      fullPath: '/notes-5'
      preLoaderRoute: typeof Notes5RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-4': {
      id: '/notes-4'
      path: '/notes-4'
      fullPath: '/notes-4'
      preLoaderRoute: typeof Notes4RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-3': {
      id: '/notes-3'
      path: '/notes-3'
      fullPath: '/notes-3'
      preLoaderRoute: typeof Notes3RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-2': {
      id: '/notes-2'
      path: '/notes-2'
      fullPath: '/notes-2'
      preLoaderRoute: typeof Notes2RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-14': {
      id: '/notes-14'
      path: '/notes-14'
      fullPath: '/notes-14'
      preLoaderRoute: typeof Notes14RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-13': {
      id: '/notes-13'
      path: '/notes-13'
      fullPath: '/notes-13'
      preLoaderRoute: typeof Notes13RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-12': {
      id: '/notes-12'
      path: '/notes-12'
      fullPath: '/notes-12'
      preLoaderRoute: typeof Notes12RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-11': {
      id: '/notes-11'
      path: '/notes-11'
      fullPath: '/notes-11'
      preLoaderRoute: typeof Notes11RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes-10': {
      id: '/notes-10'
      path: '/notes-10'
      fullPath: '/notes-10'
      preLoaderRoute: typeof Notes10RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notes': {
      id: '/notes'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof NotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homomorphisms': {
      id: '/homomorphisms'
      path: '/homomorphisms'
      fullPath: '/homomorphisms'
      preLoaderRoute: typeof HomomorphismsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecc-calculator': {
      id: '/ecc-calculator'
      path: '/ecc-calculator'
      fullPath: '/ecc-calculator'
      preLoaderRoute: typeof EccCalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dirac-notation-lab': {
      id: '/dirac-notation-lab'
      path: '/dirac-notation-lab'
      fullPath: '/dirac-notation-lab'
      preLoaderRoute: typeof DiracNotationLabRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/clock': {
      id: '/clock'
      path: '/clock'
      fullPath: '/clock'
      preLoaderRoute: typeof ClockRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ClockRoute: ClockRoute,
  DiracNotationLabRoute: DiracNotationLabRoute,
  EccCalculatorRoute: EccCalculatorRoute,
  HomomorphismsRoute: HomomorphismsRoute,
  NotesRoute: NotesRoute,
  Notes10Route: Notes10Route,
  Notes11Route: Notes11Route,
  Notes12Route: Notes12Route,
  Notes13Route: Notes13Route,
  Notes14Route: Notes14Route,
  Notes2Route: Notes2Route,
  Notes3Route: Notes3Route,
  Notes4Route: Notes4Route,
  Notes5Route: Notes5Route,
  Notes6Route: Notes6Route,
  Notes7Route: Notes7Route,
  Notes8Route: Notes8Route,
  Notes9Route: Notes9Route,
  RsaSimulationRoute: RsaSimulationRoute,
  SubgroupsRoute: SubgroupsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
